# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['main.py'],
             pathex=[],
             binaries=[],
             datas=[('fonts/pixeboy.ttf', 'fonts'),
('images/background/divine.jpg', 'images/background'),
('images/bullets/vib_bullet.jpg', 'images/bullets'),
('images/divine/divine.png', 'images/divine'),
('images/divine/flames.png', 'images/divine'),
('images/opponents/opponent.png', 'images/opponents'),
('images/victims/0.jpg', 'images/victims'),
('images/victims/1.jpg', 'images/victims'),
('images/victims/2.jpg', 'images/victims'),
('images/victims/3.jpg', 'images/victims'),
('images/victims/4.jpg', 'images/victims'),
('images/victims/5.jpg', 'images/victims'),
('images/victims/6.jpg', 'images/victims'),
('images/victims/7.jpg', 'images/victims'),
('images/victims/8.jpg', 'images/victims'),
('images/victims/9.jpg', 'images/victims'),
('images/victims/10.jpg', 'images/victims'),
('images/victims/11.jpg', 'images/victims'),
('images/victims/12.jpg', 'images/victims'),
('images/victims/13.jpg', 'images/victims'),
('images/victims/14.jpg', 'images/victims'),
('images/victims/15.jpg', 'images/victims'),
('images/victims/16.jpg', 'images/victims'),
('sounds/bullet.mp3', 'sounds'),
('sounds/short_crash.mp3', 'sounds'),
('sounds/tgchi.mp3', 'sounds'),
('sounds/ymca.mp3', 'sounds')
],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
